#!/usr/bin/env python3
"""Generate reader-facing indexes and bibliography from the curated JSON data."""
from pathlib import Path
import argparse,csv,io,json,re
from collections import Counter

ROOT=Path(__file__).resolve().parents[1]

def load():
    return tuple(json.loads((ROOT/'data'/f).read_text(encoding='utf-8')) for f in ('papers.json','taxonomy.json','repository.json'))

def cell(s):
    return str(s).replace('|','&#124;').replace('\n',' ').replace('<','&lt;').replace('>','&gt;')

def datekey(p):
    return (p['first_public_date'],p['arxiv_id'],p['id'])

def paper_link(p):
    return f"[{cell(p['id'])}]({p['url']})"

def markdown_blocks(blocks):
    """Keep table/list rows together and separate other Markdown blocks."""
    result = []
    for i, line in enumerate(blocks):
        previous = blocks[i - 1] if i else ''
        adjacent = ((line.startswith('|') and previous.startswith('|')) or
                    (line.startswith('- ') and previous.startswith('- ')))
        if i:
            result.append('\n' if adjacent else '\n\n')
        result.append(line)
    return ''.join(result) + '\n'


def localized(record, field, zh):
    return record[field + '_zh' if zh else field]


def note_link(p, zh=False, prefix='docs/'):
    filename = 'paper-notes.zh-CN.md' if zh else 'paper-notes.md'
    label = '分析' if zh else 'Analysis'
    return f'[{label}]({prefix}{filename}#{p["id"].lower()})'


def readme(papers, taxonomy, meta, zh=False):
    title = lambda t: localized(t, 'title', zh)
    notes_file = 'docs/paper-notes.zh-CN.md' if zh else 'docs/paper-notes.md'
    evidence_file = 'docs/evidence.zh-CN.md' if zh else 'docs/evidence.md'
    s = [
        '<!-- Generated by scripts/build.py; edit data/*.json and scripts/build.py. -->',
        '# Code to Everything',
        '**How Coding Agents Are Expanding Beyond Software**',
        '[English](README.md) · [中文](README.zh-CN.md)',
        f'[![Papers](https://img.shields.io/badge/papers-{len(papers)}-167D8D)](#paper-index) '
        f'[![Stars](https://img.shields.io/github/stars/DuHeng0128/Code-to-Everything?style=social)]({meta["repository"]}/stargazers)',
        '![Code to Everything: programs, execution and domain-specific feedback](assets/overview.svg)',
        ('代码智能体在视觉推理、内容创作、机器人、形式证明与科学发现中的应用。收录方法、基准与相关基础工作，整理程序表示、系统机制及实验结果。'
         if zh else 'Coding agents for visual reasoning, content creation, robotics, formal proofs and scientific discovery. A collection of methods, benchmarks and foundational work, with program representations, system mechanisms and experimental results.'),
        (f'**{len(papers)} 篇文献** · 更新于 {meta["editorial_updated"]} · [方法与实验]({notes_file}) · [跨方法比较]({evidence_file})'
         if zh else f'**{len(papers)} papers** · Updated {meta["editorial_updated"]} · [Methods and experiments]({notes_file}) · [Cross-method comparisons]({evidence_file})'),
        '[BibTeX](references.bib) · [RIS](references.ris) · [CSV](data/papers.csv) · [JSON](data/papers.json)',
        '<a id="field-map"></a>',
        '## 领域' if zh else '## Areas',
        '| 领域 | 任务 | 文献数 |' if zh else '| Area | Tasks | Papers |', '|---|---|---:|',
    ]
    counts = Counter(p['domain'] for p in papers)
    for t in taxonomy:
        s.append(f'| [{title(t)}](#{t["id"]}) | {localized(t,"description",zh)} | {counts[t["id"]]} |')
    s += [
        '<a id="paper-index"></a>',
        '## 文献与方法' if zh else '## Papers and methods',
        ('★ 标记在程序表示、执行方式或学习机制上形成代表性进展的工作，具体贡献列于论文名下。各子领域按首次公开日期倒序排列。'
         if zh else '★ marks representative advances in program representation, execution or learning; the contribution appears below the paper title. Papers are ordered by first public release within each subarea, newest first.'),
    ]
    kinds = {'method':'方法','benchmark':'基准','background':'基础','comparison':'参照','survey':'综述'}
    for t in taxonomy:
        s += [f'<a id="{t["id"]}"></a>', f'### {title(t)}', localized(t,'overview',zh)]
        for sub in t['subcategories']:
            s += [f'#### {title(sub)}',
                  '| 首次公开 | 论文 | 方法与特点 | 资源 |' if zh else '| First public | Paper | Method and features | Resources |',
                  '|---|---|---|---|']
            selected = (p for p in papers if p['domain']==t['id'] and p['subcategory']==sub['id'])
            for p in sorted(selected, key=datekey, reverse=True):
                links = [f'[Paper]({p["url"]})']
                if p['code_url']:
                    links.append(f'[Code]({p["code_url"]})')
                if p.get('project_url'):
                    links.append(f'[Project]({p["project_url"]})')
                if p.get('io'):
                    links.append(note_link(p,zh))
                kind = kinds[p['kind']] if zh else p['kind'].title()
                paper = f'**{cell(p["id"])}** · {kind}<br>{cell(p["title"])}'
                if p['milestone']:
                    paper += '<br>★ ' + cell(localized(p,'milestone_reason',zh))
                s.append(f'| {p["first_public_date"]} | {paper} | {cell(localized(p,"summary",zh))} | {" · ".join(links)} |')
    s += [
        '## 引用与贡献' if zh else '## Citations and contributions',
        ('文献引用：[BibTeX](references.bib) · [RIS](references.ris)。论文补充、方法分析与勘误见[贡献指南](CONTRIBUTING.md)。'
         if zh else 'References: [BibTeX](references.bib) · [RIS](references.ris). Paper submissions, analysis and corrections: [contribution guide](CONTRIBUTING.md).'),
        '[整理日志](docs/curation-log.md) · [分类定义](docs/taxonomy.md) · [维护说明](docs/maintenance.md)' if zh else '[Curation log](docs/curation-log.md) · [Taxonomy](docs/taxonomy.md) · [Maintenance](docs/maintenance.md)',
    ]
    return markdown_blocks(s)


def paper_notes(papers, taxonomy, zh=False):
    by_id = {p['id']:p for p in papers}
    s = ['<!-- Generated by scripts/build.py from data/papers.json and data/taxonomy.json. -->',
         '# 方法与实验' if zh else '# Methods and experiments',
         '[English](paper-notes.md) · [中文](paper-notes.zh-CN.md) · [Home](../README.md) · [中文首页](../README.zh-CN.md)']
    for t in taxonomy:
        s.append(f'- [{localized(t,"title",zh)}](#{t["id"]})')
    for t in taxonomy:
        s += [f'<a id="{t["id"]}"></a>', '## '+localized(t,'title',zh)]
        for key in t['focus_papers']:
            p = by_id[key]
            s += [f'<a id="{key.lower()}"></a>', f'### {key}', f'**[{p["title"]}]({p["url"]})** · {p["first_public_date"]}',
                  '| 项目 | 分析 |' if zh else '| Aspect | Analysis |', '|---|---|',
                  f'| {"输入与产物" if zh else "Input and output"} | {cell(localized(p,"io",zh))} |',
                  f'| {"机制" if zh else "Mechanism"} | {cell(localized(p,"mechanism" if p.get("mechanism") else "summary",zh))} |',
                  f'| {"反馈与评价" if zh else "Feedback and evaluation"} | {cell(localized(p,"feedback",zh))} |']
            if p.get('experiment'):
                s.append(f'| {"实验发现" if zh else "Experimental findings"} | {cell(localized(p,"experiment",zh))} |')
            s.append(f'| {"方法差异" if zh else "Design distinction"} | {cell(localized(p,"takeaway",zh))} |')
            related = ' · '.join(paper_link(by_id[k]) for k in p['compare_with'])
            s.append(('**相关工作：** ' if zh else '**Related work:** ')+related)
            if p.get('analysis_source'):
                s.append(('**来源：** ' if zh else '**Source:** ')+f'[{localized(p,"analysis_location",zh)}]({p["analysis_source"]})')
    return markdown_blocks(s)


def tex(s):
    mapping={'\\':r'\textbackslash{}','&':r'\&','%':r'\%','#':r'\#','_':r'\_','$':r'\$','{':r'\{','}':r'\}'}
    return ''.join(mapping.get(c,c) for c in str(s)).replace('\n',' ')

def bibliography(papers):
    bib=[];ris=[]
    for p in sorted(papers,key=lambda p:p['id'].lower()):
        note=f"Key: {p['id']}; {p['domain']}/{p['subcategory']}; {p['kind']}; first public: {p['first_public_date']}. {p['evaluation_note']}"
        for k in ['evaluation_protocol','budget_notes','human_role','checked_version','code_url','code_link_status']:
            if p.get(k):note+=' '+k+': '+p[k]
        fields={'title':'{'+tex(p['title'])+'}','author':' and '.join(tex(a) for a in p['authors']),'year':str(p['year']),'url':p['url'],'abstract':tex(p['summary']),'keywords':tex(', '.join([p['domain'],p['subcategory'],p['kind'],p['program_role']])),'note':tex(note)}
        if p['doi']:fields['doi']=p['doi']
        if p['arxiv_id']:fields.update(eprint=p['arxiv_id'],archivePrefix='arXiv')
        journal=p['venue']=='Nature'
        if p['venue']:fields['journal' if journal else 'howpublished']=tex(p['venue'])
        bib.append(('@article{' if journal else '@misc{')+p['id']+',\n'+',\n'.join('  '+k+' = {'+v+'}' for k,v in fields.items())+'\n}\n')
        record=[('TY','JOUR' if journal else 'RPRT'),('ID',p['id']),('TI',p['title'])]+[('AU',a) for a in p['authors']]+[('PY',str(p['year'])),('UR',p['url']),('AB',p['summary']),('N1',note)]
        if p['doi']:record.append(('DO',p['doi']))
        if p['venue']:record.append(('JO',p['venue']))
        if p['arxiv_id']:record.append(('N1','arXiv: '+p['arxiv_id']))
        record += [('KW',t) for t in [p['domain'],p['subcategory'],p['kind'],p['id']]]+[('ER','')]
        ris.append('\n'.join((k+'  - '+v.replace('\n',' ')).rstrip() for k,v in record)+'\n')
    return '\n'.join(bib),'\n'.join(ris)

def outputs():
    papers,taxonomy,meta=load(); bib,ris=bibliography(papers)
    stream=io.StringIO(newline='');fields=list(papers[0]);writer=csv.DictWriter(stream,fieldnames=fields,lineterminator='\n');writer.writeheader()
    for p in papers:writer.writerow({k:('; '.join(p[k]) if isinstance(p[k],list) else p[k]) for k in fields})
    return {'README.md':readme(papers,taxonomy,meta),'README.zh-CN.md':readme(papers,taxonomy,meta,True),'references.bib':bib,'references.ris':ris,'data/papers.csv':'\ufeff'+stream.getvalue(),'docs/paper-notes.md':paper_notes(papers,taxonomy),'docs/paper-notes.zh-CN.md':paper_notes(papers,taxonomy,True)}

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args();stale=[]
    for name,content in outputs().items():
        p=ROOT/name
        if args.check:
            if not p.exists() or p.read_bytes()!=content.encode('utf-8'):stale.append(name)
        else:p.write_bytes(content.encode('utf-8'))
    if stale:raise SystemExit('Stale generated files: '+', '.join(stale)+'; run python scripts/build.py')
    print('Generated files are current.' if args.check else 'Built README files, paper notes, CSV, BibTeX and RIS.')
if __name__=='__main__':main()
