#!/usr/bin/env python3
"""Generate reader-facing indexes and bibliography from the curated JSON data."""
from pathlib import Path
import argparse,csv,io,json,re
from collections import Counter

ROOT=Path(__file__).resolve().parents[1]

def load():
    return tuple(json.loads((ROOT/'data'/f).read_text(encoding='utf-8')) for f in ('papers.json','taxonomy.json','repository.json'))

def cell(s):
    return str(s).replace('|','&#124;').replace('\n',' ').replace('<','&lt;').replace('>','&gt;')

def datekey(p):
    return (p['first_public_date'],p['arxiv_id'],p['id'])

def paper_link(p):
    return f"[{cell(p['id'])}]({p['url']})"

def readme(papers,taxonomy,meta,zh=False):
    title=lambda t:t['title_zh' if zh else 'title']
    desc=lambda t:t['description_zh' if zh else 'description']
    n=len(papers); repo=meta['repository']; sections=sum(p['reading_depth']=='sections' for p in papers)
    s=['<!-- Generated by scripts/build.py; edit data/*.json and scripts/build.py. -->',
       '# Code to Everything',
       '**How Coding Agents Are Expanding Beyond Software**',
       '[English](README.md) · [中文](README.zh-CN.md)',
       f'[![Papers](https://img.shields.io/badge/papers-{n}-167D8D)](#paper-index) [![Stars](https://img.shields.io/github/stars/DuHeng0128/Code-to-Everything?style=social)]({repo}/stargazers)',
       '![Code to Everything: programs for creating, acting, and discovering](assets/overview.svg)']
    if zh:
        s += ['**Code agents正在跨越领域边界。** 它们用程序组织视觉推理、创作可编辑内容、构造三维场景、操作软件和机器人，也参与环境建模、数学证明与科学发现。本库沿着这些具体变化整理文献，追问代码在每项工作中究竟承担了什么。',
              '这里的“统一”是一条研究主线：共同使用程序，并不意味着所有领域已经由同一模型解决。既收录直接生成程序的系统，也明确标出历史基础、评估基准和互补路线。',
              f'**本次整理：{meta["updated"]}。** 广泛调研覆盖至{meta["broad_review_cutoff"]}；另于{meta["targeted_additions_date"]}补核重要遗漏和部分新作，未声称已穷尽这段时间的全部论文。当前{n}项，含{sections}项全文关键章节阅读；其余依据题名/摘要与书目记录收录。',
              '**从这里开始：** [领域地图](#field-map) · [里程碑](#milestones) · [全部文献](#paper-index) · [阅读路线](docs/reading-guide.md) · [证据比较](docs/evidence.md) · [贡献指南](CONTRIBUTING.md)',
              '📚 [BibTeX](references.bib) · [Zotero RIS](references.ris) · [CSV](data/papers.csv) · [JSON](data/papers.json)',
              '欢迎提交遗漏论文、分类建议和事实修正。如果这个整理对你有用，欢迎Star；若想参与维护，可以从一篇论文及其原始来源开始。',
              '## 更新记录',
              '- **2026-09-28**：建立双语分类目录、里程碑、证据阅读路线与统一元数据；补入12篇前史/重要遗漏及4篇9月新作。新增条目目前为摘要层核查。',
              '- 周期检索工作流会生成待审候选报告，维护者阅读确认后再收录。它不自动修改正式目录。见[维护说明](docs/maintenance.md)。']
    else:
        s += ['**Code agents are crossing domain boundaries.** They use programs to reason about images, create editable media and 3D assets, operate computers and robots, build environments, prove theorems, and advance scientific research. This collection follows those concrete developments and asks what code actually contributes.',
              'Our organizing idea is **Code Agents Unify the World**: a shared way to solve problems through programs. It is a research direction, not a claim that one model has already unified every domain. Methods, historical foundations, benchmarks and complementary approaches are labeled separately.',
              f'**Curated {meta["updated"]}.** Broad review through {meta["broad_review_cutoff"]}; targeted additions checked on {meta["targeted_additions_date"]}, not an exhaustive update of the intervening period. **{n} records**, including **{sections} with key full-text sections examined**; other entries are abstract/metadata screened.',
              '**Start here:** [Field map](#field-map) · [Milestones](#milestones) · [Paper index](#paper-index) · [Reading paths](docs/reading-guide.md) · [Evidence comparisons](docs/evidence.md) · [Contribute](CONTRIBUTING.md)',
              '📚 [BibTeX](references.bib) · [Zotero RIS](references.ris) · [CSV](data/papers.csv) · [JSON](data/papers.json)',
              'Contributions are welcome: missing papers, better classifications, and factual corrections. If this collection is useful, a star helps others find it.',
              '## Updates',
              '- **2026-09-28** — Initial bilingual collection, milestone map, evidence comparisons, and reusable metadata. Added 12 historical/missing works and four September preprints; these additions are abstract-screened.',
              '- A weekly discovery workflow prepares candidates for maintainer review. It does not automatically accept papers or rewrite the curated list. See [maintenance](docs/maintenance.md).']
    s += ['<a id="field-map"></a>', '## 领域地图' if zh else '## Field map',
          '| 领域 | 分类问题 | 条目 |' if zh else '| Area | Organizing question | Records |','|---|---|---:|']
    counts=Counter(p['domain'] for p in papers)
    for t in taxonomy:s.append(f'| [{title(t)}](#{t["id"]}) | {desc(t)} | {counts[t["id"]]} |')
    s += ['',('每篇论文只有一个主位置；跨领域关系保存在数据标签中。详细定义见[分类说明](docs/taxonomy.md)。' if zh else 'Each paper has one primary home; cross-domain connections are stored as facets. See the [taxonomy](docs/taxonomy.md) for definitions.'),'<a id="milestones"></a>','## 里程碑与主线' if zh else '## Milestones along the main thread',
          ('★表示本库选出的解释性阅读锚点，不是按被引量产生的排名，也不意味着其所有主张已获独立确认。完整脉络还应阅读各领域的前史和后续工作。' if zh else '★ marks an editorial reading anchor, not a citation ranking or an endorsement of every claim. The full index also includes precursors and follow-up work.'),
          '| 首次公开 | 工作 | 为什么放在主线中 |' if zh else '| First public | Work | What changed |','|---|---|---|']
    for p in sorted((p for p in papers if p['milestone']),key=datekey):s.append(f'| {p["first_public_date"]} | {paper_link(p)} | {cell(p["milestone_reason_zh" if zh else "milestone_reason"])} |')
    s += ['<a id="paper-index"></a>','## 全部文献' if zh else '## Paper index',
          ('**阅读标记：** K＝进入全文关键章节，A＝题名/摘要与书目核查；均不表示本库已复现实验。日期优先采用首次公开时间，预印本与发表版合并；月份精度不会补造具体日期。完整作者、版本、检查日期和协议备注见JSON/CSV及文献导出。' if zh else '**Reading labels:** K = key full-text sections examined; A = abstract/metadata screened. Neither means independently reproduced. Dates refer to first public release where known; month-level dates are not padded with invented days. Full authors, versions, check dates and protocol notes are in JSON/CSV and bibliography exports.'),
          ('**类型：** Method＝方法；Benchmark＝基准/数据；Background＝历史基础；Comparison＝互补/边界路线；Survey＝综述。新作与历史里程碑同时保留，每个子类按首次公开时间倒序。' if zh else '**Types:** Method, Benchmark, Background, Comparison, Survey. Historical milestones remain visible alongside new papers; each subsection is sorted by first public date, newest first.')]
    for t in taxonomy:
        s += [f'<a id="{t["id"]}"></a>',f'### {title(t)}',desc(t)]
        for sub in t['subcategories']:
            s += [f'#### {title(sub)}', '| 日期 | 论文 / 类型 | 代码的作用 | 收录理由 | 资源 |' if zh else '| Date | Paper / type | Role of code | Why it belongs | Resources |','|---|---|---|---|---|']
            for p in sorted((p for p in papers if p['domain']==t['id'] and p['subcategory']==sub['id']),key=datekey,reverse=True):
                label='K' if p['reading_depth']=='sections' else 'A'; star='★ ' if p['milestone'] else ''
                links=[f'[Paper]({p["url"]})']
                if p['code_url']:links.append(f'[Code]({p["code_url"]})')
                if p.get('project_url'):links.append(f'[Project]({p["project_url"]})')
                s.append(f'| {p["first_public_date"]} | {star}**{cell(p["id"])}** · {p["kind"].title()} · {label}<br>{cell(p["title"])} | {cell(p["program_role"])} | {cell(p["summary_zh" if zh else "summary"])} | {" · ".join(links)} |')
    s += ['## Citation & reuse',
          ('综述暂定标题为 *Code to Everything: How Coding Agents Are Expanding Beyond Software*，尚未提供公开稿件引用。请直接引用原始论文；稿件发布后再补充正式citation。BibTeX与RIS由同一数据源生成，不把仓库占位信息伪装成已发表论文。' if zh else 'The survey working title is *Code to Everything: How Coding Agents Are Expanding Beyond Software*. No public manuscript citation is available yet. Please cite the original papers; a survey citation will be added after release. The exports contain the actual literature, not an invented survey citation.'),
          '## Contributing',
          ('请查看[收录与维护规范](CONTRIBUTING.md)。提交时说明模型生成/修改了什么、由什么执行、如何检查，以及你核到了摘要还是全文。也欢迎修正分类和补齐重要前史。' if zh else 'See [CONTRIBUTING.md](CONTRIBUTING.md). Explain what the model generates or edits, what executes it, how it is checked, and whether you examined the abstract or full text. Corrections and missing historical work are especially welcome.'),
          '## Acknowledgments',
          'The collection format is informed by [MLLM-Token-Compression](https://github.com/yaolinli/MLLM-Token-Compression). This repository develops its own domain taxonomy, annotations and evidence comparisons. Papers and linked software remain the work of their respective authors.']
    result=[]
    for i,line in enumerate(s):
        previous=s[i-1] if i else ''
        adjacent=(line.startswith('|') and previous.startswith('|')) or (line.startswith('- ') and previous.startswith('- '))
        if i:result.append('\n' if adjacent else '\n\n')
        result.append(line)
    return ''.join(result)+'\n'

def tex(s):
    mapping={'\\':r'\textbackslash{}','&':r'\&','%':r'\%','#':r'\#','_':r'\_','$':r'\$','{':r'\{','}':r'\}'}
    return ''.join(mapping.get(c,c) for c in str(s)).replace('\n',' ')

def bibliography(papers):
    bib=[];ris=[]
    for p in sorted(papers,key=lambda p:p['id'].lower()):
        note=f"Key: {p['id']}; {p['domain']}/{p['subcategory']}; {p['kind']}; reading: {p['reading_depth']}; checked: {p['checked_on']}; first public: {p['first_public_date']}. {p['evaluation_note']}"
        for k in ['evaluation_protocol','budget_notes','human_role','checked_version','code_url','code_link_status']:
            if p.get(k):note+=' '+k+': '+p[k]
        fields={'title':'{'+tex(p['title'])+'}','author':' and '.join(tex(a) for a in p['authors']),'year':str(p['year']),'url':p['url'],'abstract':tex(p['summary']),'keywords':tex(', '.join([p['domain'],p['subcategory'],p['kind'],p['program_role']])),'note':tex(note)}
        if p['doi']:fields['doi']=p['doi']
        if p['arxiv_id']:fields.update(eprint=p['arxiv_id'],archivePrefix='arXiv')
        journal=p['venue']=='Nature'
        if p['venue']:fields['journal' if journal else 'howpublished']=tex(p['venue'])
        bib.append(('@article{' if journal else '@misc{')+p['id']+',\n'+',\n'.join('  '+k+' = {'+v+'}' for k,v in fields.items())+'\n}\n')
        record=[('TY','JOUR' if journal else 'RPRT'),('ID',p['id']),('TI',p['title'])]+[('AU',a) for a in p['authors']]+[('PY',str(p['year'])),('UR',p['url']),('AB',p['summary']),('N1',note)]
        if p['doi']:record.append(('DO',p['doi']))
        if p['venue']:record.append(('JO',p['venue']))
        if p['arxiv_id']:record.append(('N1','arXiv: '+p['arxiv_id']))
        record += [('KW',t) for t in [p['domain'],p['subcategory'],p['kind'],p['id']]]+[('ER','')]
        ris.append('\n'.join((k+'  - '+v.replace('\n',' ')).rstrip() for k,v in record)+'\n')
    return '\n'.join(bib),'\n'.join(ris)

def outputs():
    papers,taxonomy,meta=load(); bib,ris=bibliography(papers)
    stream=io.StringIO(newline='');fields=list(papers[0]);writer=csv.DictWriter(stream,fieldnames=fields,lineterminator='\n');writer.writeheader()
    for p in papers:writer.writerow({k:('; '.join(p[k]) if isinstance(p[k],list) else p[k]) for k in fields})
    return {'README.md':readme(papers,taxonomy,meta),'README.zh-CN.md':readme(papers,taxonomy,meta,True),'references.bib':bib,'references.ris':ris,'data/papers.csv':'\ufeff'+stream.getvalue()}

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args();stale=[]
    for name,content in outputs().items():
        p=ROOT/name
        if args.check:
            if not p.exists() or p.read_bytes()!=content.encode('utf-8'):stale.append(name)
        else:p.write_bytes(content.encode('utf-8'))
    if stale:raise SystemExit('Stale generated files: '+', '.join(stale)+'; run python scripts/build.py')
    print('Generated files are current.' if args.check else 'Built README files, CSV, BibTeX and RIS.')
if __name__=='__main__':main()
